services:
  web:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - "./server/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./server/nginx/conf.d:/etc/nginx/conf.d"
      - "./server/nginx/log:/var/log/nginx"
      - "./wordpress:/var/www/html"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./server/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Admin@123
      WORDPRESS_DB_NAME: wordpress
      TZ: Asia/Tokyo
    volumes:
      - "./wordpress:/var/www/html"
      - "./server/wordpress/php/php.ini:/usr/local/etc/php/php.ini"
      - "./server/wordpress/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7.40
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
      TZ: Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
      - "./server/mysql/log:/var/log/mysql"
      - "./server/mysql/conf.d:/etc/mysql/conf.d"
volumes:
  db: